server:
  port: 8770
  shutdown: graceful

spring:
  application:
    name: FILE-MS

  servlet:
    multipart:
      enabled: true
      max-file-size: 3072KB
      max-request-size: 3072KB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update

file:
  upload-path: 'C:\Users\user\Desktop\document'

application:
  translation:
    properties:
      baseName: message
      defaultLocale: uz